<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Account Sheet Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f5f5f5;
        }

        .amount {
            text-align: right;
        }

        .credit {
            color: #10B981;
        }

        .debit {
            color: #EF4444;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-style: italic;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Account Sheet Report</h1>
        @if($account)
        <h2>{{ $account->name }}</h2>
        @else
        <h2>All Accounts</h2>
        @endif
        <p>Generated on {{ now()->format('F j, Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Type</th>
                <th>Category</th>
                <th>Reference</th>
                <th>Amount</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $transaction)
            <tr>
                <td>{{ $transaction->transaction_date->format('M j, Y') }}</td>
                <td>{{ $transaction->description }}</td>
                <td>{{ ucfirst($transaction->type) }}</td>
                <td>{{ $transaction->category }}</td>
                <td>{{ $transaction->reference_number }}</td>
                <td class="amount {{ $transaction->type }}">
                    GMD {{ number_format($transaction->amount, 2) }}
                </td>
                <td class="amount">
                    GMD {{ number_format($transaction->running_balance, 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5"><strong>Total</strong></td>
                <td class="amount">
                    GMD {{ number_format($transactions->sum('amount'), 2) }}
                </td>
                <td class="amount">
                    GMD {{ number_format($transactions->last()->running_balance ?? 0, 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>This report was automatically generated by the Finance Management System.</p>
    </div>
</body>

</html>