<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Cash Flow Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f5f5f5;
        }

        .amount {
            text-align: right;
        }

        .credit {
            color: #10B981;
        }

        .debit {
            color: #EF4444;
        }

        .net-positive {
            color: #10B981;
            font-weight: bold;
        }

        .net-negative {
            color: #EF4444;
            font-weight: bold;
        }

        .summary {
            margin: 20px 0;
            padding: 10px;
            background-color: #f5f5f5;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-style: italic;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Cash Flow Report</h1>
        <h2>{{ ucfirst($summaryType) }} Summary</h2>
        <p>Generated on {{ now()->format('F j, Y') }}</p>
    </div>

    <div class="summary">
        <h3>Overall Summary</h3>
        @php
        $totalCredits = $transactions->map(function($group) {
        return $group->where('type', 'credit')->sum('amount');
        })->sum();
        $totalDebits = $transactions->map(function($group) {
        return $group->where('type', 'debit')->sum('amount');
        })->sum();
        $netFlow = $totalCredits - $totalDebits;
        @endphp
        <p>
            <strong>Total Credits:</strong>
            <span class="credit">GMD {{ number_format($totalCredits, 2) }}</span>
        </p>
        <p>
            <strong>Total Debits:</strong>
            <span class="debit">GMD {{ number_format($totalDebits, 2) }}</span>
        </p>
        <p>
            <strong>Net Cash Flow:</strong>
            <span class="{{ $netFlow >= 0 ? 'net-positive' : 'net-negative' }}">
                GMD {{ number_format($netFlow, 2) }}
            </span>
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Period</th>
                <th>Credits</th>
                <th>Debits</th>
                <th>Net Flow</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $period => $group)
            @php
            $credits = $group->where('type', 'credit')->sum('amount');
            $debits = $group->where('type', 'debit')->sum('amount');
            $netFlow = $credits - $debits;
            @endphp
            <tr>
                <td>{{ $period }}</td>
                <td class="amount credit">
                    GMD {{ number_format($credits, 2) }}
                </td>
                <td class="amount debit">
                    GMD {{ number_format($debits, 2) }}
                </td>
                <td class="amount {{ $netFlow >= 0 ? 'net-positive' : 'net-negative' }}">
                    GMD {{ number_format($netFlow, 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td><strong>Total</strong></td>
                <td class="amount credit">
                    GMD {{ number_format($totalCredits, 2) }}
                </td>
                <td class="amount debit">
                    GMD {{ number_format($totalDebits, 2) }}
                </td>
                <td class="amount {{ $netFlow >= 0 ? 'net-positive' : 'net-negative' }}">
                    GMD {{ number_format($netFlow, 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>This report was automatically generated by the Finance Management System.</p>
    </div>
</body>

</html>