<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Expense Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f5f5f5;
        }

        .amount {
            text-align: right;
            color: #EF4444;
        }

        .summary {
            margin: 20px 0;
            padding: 10px;
            background-color: #f5f5f5;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-style: italic;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Expense Claims Report</h1>
        @if(!empty($filters['category']))
        <h2>Category: {{ $filters['category'] }}</h2>
        @else
        <h2>All Categories</h2>
        @endif
        <p>Generated on {{ now()->format('F j, Y') }}</p>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <p>
            <strong>Total Amount:</strong>
            GMD {{ number_format($expenses->sum('total'), 2) }}
        </p>
        <p>
            <strong>Number of Claims:</strong>
            {{ $expenses->count() }}
        </p>
        <p>
            <strong>Status Breakdown:</strong><br>
            @foreach($expenses->groupBy('status') as $status => $claims)
            {{ ucfirst($status) }}: {{ $claims->count() }} claims (GMD {{ number_format($claims->sum('total'), 2) }})<br>
            @endforeach
        </p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Claim Date</th>
                <th>Title</th>
                <th>Reference ID</th>
                <th>Payee</th>
                <th>Status</th>
                <th>Bank Account</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($expenses as $expense)
            <tr>
                <td>{{ $expense->claim_date?->format('M j, Y') ?? 'N/A' }}</td>
                <td>{{ $expense->title }}</td>
                <td>{{ $expense->reference_id }}</td>
                <td>{{ $expense->payee }}</td>
                <td>{{ ucfirst($expense->status) }}</td>
                <td>{{ $expense->bankAccount?->name ?? 'N/A' }}</td>
                <td class="amount">
                    GMD {{ number_format($expense->total, 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="6"><strong>Total</strong></td>
                <td class="amount">
                    GMD {{ number_format($expenses->sum('total'), 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>This report was automatically generated by the Finance Management System.</p>
    </div>
</body>

</html>