<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Expense Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f5f5f5;
        }

        .amount {
            text-align: right;
            color: #EF4444;
        }

        .summary {
            margin: 20px 0;
            padding: 10px;
            background-color: #f5f5f5;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-style: italic;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Expense Report</h1>
        @if($category)
        <h2>Category: {{ $category }}</h2>
        @else
        <h2>All Categories</h2>
        @endif
        <p>Generated on {{ now()->format('F j, Y') }}</p>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <p>
            <strong>Total Expenses:</strong>
            GMD {{ number_format($expenses->sum('amount'), 2) }}
        </p>
        <p>
            <strong>Number of Transactions:</strong>
            {{ $expenses->count() }}
        </p>
        @if(!$category)
        <p>
            <strong>Top Categories:</strong><br>
            @foreach($expenses->groupBy('category')->map->sum('amount')->sortDesc()->take(5) as $cat => $amount)
            {{ $cat }}: GMD {{ number_format($amount, 2) }}<br>
            @endforeach
        </p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Category</th>
                <th>Reference</th>
                <th>Account</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($expenses as $expense)
            <tr>
                <td>{{ $expense->transaction_date->format('M j, Y') }}</td>
                <td>{{ $expense->description }}</td>
                <td>{{ $expense->category }}</td>
                <td>{{ $expense->reference_number }}</td>
                <td>{{ $expense->bankAccount->name }}</td>
                <td class="amount">
                    GMD {{ number_format($expense->amount, 2) }}
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5"><strong>Total</strong></td>
                <td class="amount">
                    GMD {{ number_format($expenses->sum('amount'), 2) }}
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        <p>This report was automatically generated by the Finance Management System.</p>
    </div>
</body>

</html>